# SPDX-FileCopyrightText: 2026 Canonical Ltd
# SPDX-License-Identifier: GPL-3.0-only

name: Prepare the REST OpenAPI Specification
on:
  repository_dispatch:
    types: [openapi-updated]

jobs:
  process-specification:
    runs-on: ubuntu-latest
    name: Bundle REST API documentation
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: canonical/snapd
          path: ./snapd
          fetch-depth: 0

      - name: Check Licensing/Copyright Compliance
        uses: docker://fsfe/reuse
        with:
          entrypoint: /bin/sh
          args: -c "cd docs/api && reuse lint"

      - name: Lint API specification
        uses: docker://redocly/cli
        with:
          args: lint ./docs/api/openapi.yaml

      - name: Bundle OpenAPI to JSON
        uses: docker://redocly/cli
        with:
          args: bundle ./docs/api/openapi.yaml --output ./docs/api/openapi.json --ext json

      - name: Store generated JSON artifact
        uses: actions/upload-artifact@v6
        with:
          name: openapi-spec
          path: docs/api/openapi.json
